# -*- coding: utf-8 -*-
"""
Ocean ERP - Account Report Views
=================================

Views for account report management.
"""

from core_framework.ui import View, TreeView, FormView, SearchView, KanbanView
from core_framework.actions import ActWindow


class AccountReportTreeView(TreeView):
    """Account Report Tree View"""
    
    _name = 'account.report.tree'
    _model = 'account.report'
    _title = 'Financial Reports'
    
    def get_columns(self):
        """Get tree view columns"""
        return [
            {'name': 'name', 'label': 'Report Name', 'width': 200},
            {'name': 'report_type', 'label': 'Report Type', 'width': 150},
            {'name': 'date_from', 'label': 'From Date', 'width': 100},
            {'name': 'date_to', 'label': 'To Date', 'width': 100},
            {'name': 'state', 'label': 'Status', 'width': 100},
            {'name': 'target_move', 'label': 'Target Moves', 'width': 120},
            {'name': 'display_detail', 'label': 'Display Detail', 'width': 120},
            {'name': 'generated_date', 'label': 'Generated Date', 'width': 120},
            {'name': 'generated_by', 'label': 'Generated By', 'width': 120},
            {'name': 'age_group', 'label': 'Age Group', 'width': 100},
            {'name': 'size', 'label': 'Size', 'width': 80},
            {'name': 'season', 'label': 'Season', 'width': 100},
            {'name': 'brand', 'label': 'Brand', 'width': 100},
            {'name': 'color', 'label': 'Color', 'width': 100},
        ]
    
    def get_decorations(self):
        """Get tree view decorations"""
        return {
            'draft': {'color': 'gray'},
            'generated': {'color': 'green'},
            'cancelled': {'color': 'red'},
        }


class AccountReportFormView(FormView):
    """Account Report Form View"""
    
    _name = 'account.report.form'
    _model = 'account.report'
    _title = 'Financial Report'
    
    def get_fields(self):
        """Get form view fields"""
        return [
            {
                'name': 'name',
                'label': 'Report Name',
                'type': 'char',
                'required': True,
            },
            {
                'name': 'report_type',
                'label': 'Report Type',
                'type': 'selection',
                'required': True,
            },
            {
                'name': 'date_from',
                'label': 'From Date',
                'type': 'datetime',
                'required': True,
            },
            {
                'name': 'date_to',
                'label': 'To Date',
                'type': 'datetime',
                'required': True,
            },
            {
                'name': 'state',
                'label': 'Status',
                'type': 'selection',
                'readonly': True,
            },
            {
                'name': 'target_move',
                'label': 'Target Moves',
                'type': 'selection',
            },
            {
                'name': 'display_detail',
                'label': 'Display Detail',
                'type': 'selection',
            },
            {
                'name': 'generated_date',
                'label': 'Generated Date',
                'type': 'datetime',
                'readonly': True,
            },
            {
                'name': 'generated_by',
                'label': 'Generated By',
                'type': 'many2one',
                'readonly': True,
            },
            {
                'name': 'age_group',
                'label': 'Age Group',
                'type': 'selection',
            },
            {
                'name': 'size',
                'label': 'Size',
                'type': 'selection',
            },
            {
                'name': 'season',
                'label': 'Season',
                'type': 'selection',
            },
            {
                'name': 'brand',
                'label': 'Brand',
                'type': 'char',
            },
            {
                'name': 'color',
                'label': 'Color',
                'type': 'char',
            },
            {
                'name': 'company_id',
                'label': 'Company',
                'type': 'many2one',
            },
            {
                'name': 'currency_id',
                'label': 'Currency',
                'type': 'many2one',
            },
        ]
    
    def get_buttons(self):
        """Get form view buttons"""
        return [
            {
                'name': 'action_generate',
                'label': 'Generate Report',
                'type': 'object',
                'class': 'btn-primary',
                'attrs': {'invisible': [('state', '!=', 'draft')]},
            },
            {
                'name': 'action_cancel',
                'label': 'Cancel',
                'type': 'object',
                'class': 'btn-danger',
                'attrs': {'invisible': [('state', '=', 'generated')]},
            },
            {
                'name': 'action_view_lines',
                'label': 'View Report Lines',
                'type': 'object',
                'class': 'btn-info',
                'attrs': {'invisible': [('state', '!=', 'generated')]},
            },
        ]


class AccountReportSearchView(SearchView):
    """Account Report Search View"""
    
    _name = 'account.report.search'
    _model = 'account.report'
    _title = 'Search Financial Reports'
    
    def get_fields(self):
        """Get search view fields"""
        return [
            {'name': 'name', 'label': 'Report Name'},
            {'name': 'report_type', 'label': 'Report Type'},
            {'name': 'state', 'label': 'Status'},
            {'name': 'generated_by', 'label': 'Generated By'},
            {'name': 'age_group', 'label': 'Age Group'},
            {'name': 'size', 'label': 'Size'},
            {'name': 'season', 'label': 'Season'},
            {'name': 'brand', 'label': 'Brand'},
            {'name': 'color', 'label': 'Color'},
        ]
    
    def get_filters(self):
        """Get search view filters"""
        return [
            {'name': 'draft', 'label': 'Draft', 'domain': [('state', '=', 'draft')]},
            {'name': 'generated', 'label': 'Generated', 'domain': [('state', '=', 'generated')]},
            {'name': 'cancelled', 'label': 'Cancelled', 'domain': [('state', '=', 'cancelled')]},
            {'name': 'profit_loss', 'label': 'Profit & Loss', 'domain': [('report_type', '=', 'profit_loss')]},
            {'name': 'balance_sheet', 'label': 'Balance Sheet', 'domain': [('report_type', '=', 'balance_sheet')]},
            {'name': 'cash_flow', 'label': 'Cash Flow', 'domain': [('report_type', '=', 'cash_flow')]},
            {'name': 'trial_balance', 'label': 'Trial Balance', 'domain': [('report_type', '=', 'trial_balance')]},
            {'name': 'aged_receivables', 'label': 'Aged Receivables', 'domain': [('report_type', '=', 'aged_receivables')]},
            {'name': 'aged_payables', 'label': 'Aged Payables', 'domain': [('report_type', '=', 'aged_payables')]},
            {'name': 'inventory_valuation', 'label': 'Inventory Valuation', 'domain': [('report_type', '=', 'inventory_valuation')]},
            {'name': 'sales_by_age', 'label': 'Sales by Age Group', 'domain': [('report_type', '=', 'sales_by_age')]},
            {'name': 'sales_by_size', 'label': 'Sales by Size', 'domain': [('report_type', '=', 'sales_by_size')]},
            {'name': 'sales_by_brand', 'label': 'Sales by Brand', 'domain': [('report_type', '=', 'sales_by_brand')]},
            {'name': 'sales_by_color', 'label': 'Sales by Color', 'domain': [('report_type', '=', 'sales_by_color')]},
            {'name': 'sales_by_season', 'label': 'Sales by Season', 'domain': [('report_type', '=', 'sales_by_season')]},
            {'name': 'cost_analysis', 'label': 'Cost Analysis', 'domain': [('report_type', '=', 'cost_analysis')]},
            {'name': 'profitability_analysis', 'label': 'Profitability Analysis', 'domain': [('report_type', '=', 'profitability_analysis')]},
            {'name': 'seasonal_analysis', 'label': 'Seasonal Analysis', 'domain': [('report_type', '=', 'seasonal_analysis')]},
            {'name': 'age_0_2', 'label': 'Baby (0-2 years)', 'domain': [('age_group', '=', '0-2')]},
            {'name': 'age_2_4', 'label': 'Toddler (2-4 years)', 'domain': [('age_group', '=', '2-4')]},
            {'name': 'age_4_6', 'label': 'Pre-school (4-6 years)', 'domain': [('age_group', '=', '4-6')]},
            {'name': 'summer', 'label': 'Summer', 'domain': [('season', '=', 'summer')]},
            {'name': 'winter', 'label': 'Winter', 'domain': [('season', '=', 'winter')]},
            {'name': 'monsoon', 'label': 'Monsoon', 'domain': [('season', '=', 'monsoon')]},
        ]
    
    def get_groups(self):
        """Get search view groups"""
        return [
            {'name': 'report_type', 'label': 'Report Type'},
            {'name': 'state', 'label': 'Status'},
            {'name': 'generated_by', 'label': 'Generated By'},
            {'name': 'age_group', 'label': 'Age Group'},
            {'name': 'size', 'label': 'Size'},
            {'name': 'season', 'label': 'Season'},
            {'name': 'brand', 'label': 'Brand'},
            {'name': 'color', 'label': 'Color'},
            {'name': 'company_id', 'label': 'Company'},
        ]


class AccountReportKanbanView(KanbanView):
    """Account Report Kanban View"""
    
    _name = 'account.report.kanban'
    _model = 'account.report'
    _title = 'Financial Reports'
    
    def get_kanban_columns(self):
        """Get kanban view columns"""
        return [
            {'name': 'state', 'label': 'Status'},
            {'name': 'report_type', 'label': 'Report Type'},
        ]
    
    def get_kanban_fields(self):
        """Get kanban view fields"""
        return [
            'state',
            'report_type',
            'name',
            'date_from',
            'date_to',
            'target_move',
            'display_detail',
            'generated_date',
            'generated_by',
            'age_group',
            'size',
            'season',
            'brand',
            'color',
        ]


class AccountReportActWindow(ActWindow):
    """Account Report Action Window"""
    
    _name = 'action_account_report'
    _model = 'account.report'
    _view_mode = 'tree,form,kanban'
    _title = 'Financial Reports'
    
    def get_context(self):
        """Get action window context"""
        return {}
    
    def get_domain(self):
        """Get action window domain"""
        return []
    
    def get_help(self):
        """Get action window help"""
        return {
            'title': 'Create your first financial report!',
            'message': 'Financial reports help you analyze your business performance.',
        }


class AccountReportLineTreeView(TreeView):
    """Account Report Line Tree View"""
    
    _name = 'account.report.line.tree'
    _model = 'account.report.line'
    _title = 'Report Lines'
    
    def get_columns(self):
        """Get tree view columns"""
        return [
            {'name': 'report_id', 'label': 'Report', 'width': 150},
            {'name': 'name', 'label': 'Line Name', 'width': 200},
            {'name': 'code', 'label': 'Code', 'width': 100},
            {'name': 'level', 'label': 'Level', 'width': 80},
            {'name': 'amount', 'label': 'Amount', 'width': 100},
            {'name': 'currency_id', 'label': 'Currency', 'width': 100},
            {'name': 'age_group', 'label': 'Age Group', 'width': 100},
            {'name': 'size', 'label': 'Size', 'width': 80},
            {'name': 'season', 'label': 'Season', 'width': 100},
            {'name': 'brand', 'label': 'Brand', 'width': 100},
            {'name': 'color', 'label': 'Color', 'width': 100},
        ]
    
    def get_decorations(self):
        """Get tree view decorations"""
        return {
            'level_0': {'color': 'black'},
            'level_1': {'color': 'blue'},
            'level_2': {'color': 'green'},
            'level_3': {'color': 'orange'},
        }


class AccountReportLineFormView(FormView):
    """Account Report Line Form View"""
    
    _name = 'account.report.line.form'
    _model = 'account.report.line'
    _title = 'Report Line'
    
    def get_fields(self):
        """Get form view fields"""
        return [
            {
                'name': 'report_id',
                'label': 'Report',
                'type': 'many2one',
                'required': True,
            },
            {
                'name': 'sequence',
                'label': 'Sequence',
                'type': 'integer',
            },
            {
                'name': 'name',
                'label': 'Line Name',
                'type': 'char',
                'required': True,
            },
            {
                'name': 'code',
                'label': 'Code',
                'type': 'char',
            },
            {
                'name': 'level',
                'label': 'Level',
                'type': 'integer',
            },
            {
                'name': 'amount',
                'label': 'Amount',
                'type': 'float',
            },
            {
                'name': 'currency_id',
                'label': 'Currency',
                'type': 'many2one',
            },
            {
                'name': 'age_group',
                'label': 'Age Group',
                'type': 'selection',
            },
            {
                'name': 'size',
                'label': 'Size',
                'type': 'selection',
            },
            {
                'name': 'season',
                'label': 'Season',
                'type': 'selection',
            },
            {
                'name': 'brand',
                'label': 'Brand',
                'type': 'char',
            },
            {
                'name': 'color',
                'label': 'Color',
                'type': 'char',
            },
            {
                'name': 'company_id',
                'label': 'Company',
                'type': 'many2one',
            },
        ]


class AccountReportLineActWindow(ActWindow):
    """Account Report Line Action Window"""
    
    _name = 'action_account_report_line'
    _model = 'account.report.line'
    _view_mode = 'tree,form'
    _title = 'Report Lines'
    
    def get_context(self):
        """Get action window context"""
        return {}
    
    def get_domain(self):
        """Get action window domain"""
        return []
    
    def get_help(self):
        """Get action window help"""
        return {
            'title': 'View report lines!',
            'message': 'Report lines show the details of each report.',
        }